### ISSUE TITLE
discord-lite.exe detected as dangerous by Windows Defender

### ISSUE THREAD

**Issue by Katzenwerfer** [Sachit71/Discord-Lite#15]
The executable of the program is detected as dangerous by Windows Defender.
It is also detected as such if scanned with VirusTotal.

A screenshot from Defender is attached for more information.
![image](https://user-images.githubusercontent.com/53267697/157688465-48f75723-a41f-4ea5-a76a-510182683eff.png)

**Comment by Sachit71** [comment]
Hello there, Discord Lite, the exe file is an unsigned executable, to buy a signature or certificate from Microsoft, monetary support is required, since its an open source project, we cannot get a certificate from Microsoft, hence windows defender flags it as an unwanted application, you can build from source if you still think it is unsafe.

**Comment by Sachit71** [comment]
I will be closing this issue because of no response from @Katzenwerfer hopefully your doubt has been solved.
