### ISSUE TITLE
Mic not working and detect

### ISSUE THREAD

**Issue by Bristolridge** [Sachit71/Discord-Lite#3]
Hello, how to fix this mic not detect?

![image](https://user-images.githubusercontent.com/97235304/148391145-13b747ee-a221-426d-9a1c-1d04b957ea4c.png)

**Comment by Sachit71** [comment]
Heya, if you read the documentation closely, you'll notice `drawbacks` so, uhm for this version, there is no solution for it(As of now) we are working on it.
I will leave this issue open to notify you on further updates, sorry for the inconvenience.

**Comment by Sachit71** [comment]
Heya, sachit here, I fixed this and will be making a new release, will be packaged tomorrow :D

**Comment by Sachit71** [comment]
Code published to GitHub and PyPi https://pypi.org/project/discord-lite/, you will receive the binary executable by tomorrow.

**Comment by terracraft321** [comment]
Does the v1 installer, install the current v1.2 version or is there a way of implementing an auto-update?

**Comment by Sachit71** [comment]
Heya the v1 installer doesn't install the v1.1 application, we're still packaging that, as for the .ico thanks for the suggestion we'll be using a better quality icon and nothing can be done about the bar since it's the default windows GUI created by the QT engine. Auto update seems like a nice idea we'll see what can be done about it, but don't worry we won't be making new releases frequently, hope this answers all your questions 😄

**Comment by Sachit71** [comment]
@Bristolridge issues solved, newer version has been updated, lemme know if there are anymore issues :D
